# Generated by Django 5.2.3 on 2025-06-16 05:01

from django.db import migrations
import random


def add_users(apps, schema_editor):
    User = apps.get_model("backend", "User")
    Country = apps.get_model("backend", "Country")

    if User.objects.count() == 0:
        for i in range(1, 6):
            user = User.objects.create(username=f"user{i}@example.com")
            user.save()

    users = list(User.objects.all())
    countries = Country.objects.all()

    for i in countries:
        i.user = random.choice(users)
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_country_user"),
    ]

    operations = [migrations.RunPython(add_users, migrations.RunPython.noop)]
