# Generated by Django 5.2.3 on 2025-06-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_populating_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
