# Generated by Django 5.2.3 on 2025-06-16 05:56

from django.db import migrations


def add_password_field(apps, schema_editor):
    User = apps.get_model("backend", "User")
    for user in User.objects.all():
        user.password = "password123"
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_passadd"),
    ]

    operations = [migrations.RunPython(add_password_field, migrations.RunPython.noop)]
