# Generated by Django 5.2.3 on 2025-06-16 06:16

from django.db import migrations
from django.contrib.auth.hashers import make_password

def hash_passwords(apps, schema_editor):
    User = apps.get_model("backend", "User")
    for user in User.objects.all():
        if user.password :
            user.password = make_password(user.password)
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_passaddagain"),
    ]

    operations = [
        migrations.RunPython(hash_passwords, migrations.RunPython.noop),
    ]
