# name: Build Docker Images and Push to ACR
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Log in to Azure Container Registry
#         uses: azure/docker-login@v1
#         with:
#           login-server: ${{ secrets.ACR_LOGIN_SERVER }}
#           username: ${{ secrets.ACR_USERNAME }}
#           password: ${{ secrets.ACR_PASSWORD }}

#       - name: Build and push Docker image
#         run: |
#           docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/django-server:latest .
#           docker push ${{ secrets.ACR_LOGIN_SERVER }}/django-server:latest
